### ISSUE TITLE
when to use hasOwnProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#99]
Over in https://github.com/phetsims/phet-info/issues/96, @samreid @zepumph and I identified some "best practices" for `options`, including:

> • To check for existence of an option, use `hasOwnProperty( 'field' )` instead of `!options.field` or `options.field === undefined`.

Now that I've had a chance to test-drive this use of `hasOwnProperty`, I think we need to take a closer look at whether using `hasOwnProperty` is necessary. 

* It makes assertions more verbose. Comparison:

```js
assert && assert( options.hasOwnProperty( 'children' ), 'some message' );
assert && assert( !options.children, 'some message' );
assert && assert( options.children === undefined, 'some message' );
```

* It requires a string value, which presents additional challenges when renaming an option.  See above example. 

* It may be unnecessary. `hasOwnProperty` returns a boolean indicating whether the object has the specified property as its own property, as opposed to inheriting it.  With `options`, we're dealing with object literals, so there's no inheritance involved.   So is it necessary to use `hasOwnProperty`?

* In what situations (other than `options`) should we be using `hasOwnProperty`?

**Comment by pixelzoom** [comment]
I see surprisingly few uses of `hasOwnProperty` across sim and common code.  And I see only 7 uses in scenery, so it would be nice to have @jonathanolson chime in.

**Comment by samreid** [comment]
The main issue is that using the not operator is problematic for options that are falsy.  For example:
```js
new MyType({time:0})
// ...
// in MyType constructor
assert && assert( !options.time, 'some message').
```

The code probably intended to check that `options.time` wasn't specified, but since `!0` is `true` this assertion will not work as expected.  Same problem for boolean options.  An occurrence of this problem was identified and resolved in https://github.com/phetsims/phet-io-wrappers/commit/57382002ffc800b85d41f729f6e374116578ce0a

Regarding undefined, we have (a) chosen as a policy not to use `undefined` as a value (like `new MyNode({name:undefined})` and (b) we are using `'use strict'` so it we cannot accidentally redefine the `undefined` value globally.  Therefore, we could likely use `options.children === undefined`.  

I'm not sure about the other points you raised.  Would be good to discuss.

**Comment by jonathanolson** [comment]
It seems to me that for options, we should generally be using "raw" POJO objects. Since they don't use prototypical inheritance (basically, they still have the Object prototype), I don't see a point of checking hasOwnProperty on that type of thing.

To me it IS useful if iterating over keys of something. We don't want to pick up a library dependency that adds something enumerable to the Object prototype and have our code break. But if it's an already-known key, checking hasOwnProperty doesn't seem helpful to me.

**Comment by pixelzoom** [comment]
4/4/19 dev meeting:

Using `hasOwnProperty` is not required. Use an assertion expression that is semantically correct, and avoids "falsy" gotchas.   Booleans, the number zero, and empty string can all be falsy.  More on falsy at https://developer.mozilla.org/en-US/docs/Glossary/Falsy.

I will update the options "best practices" in #96.
